#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "%%BINPATH%%" "$@"
  ret=$?
else
  node  "%%BINPATH%%" "$@"
  ret=$?
fi
exit $ret
